# fly.toml app configuration file generated for jobscout-api on 2026-01-08T16:22:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobscout-api'
primary_region = 'iad'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  JOBSCOUT_DEBUG = 'false'
  JOBSCOUT_SCRAPE_INTERVAL_HOURS = '6'
  JOBSCOUT_USE_SQLITE = 'false'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
